# Parameters used to generate this project with aem-project-archetype

groupId=com.aem.ecm
artifactId=ecm
version=1.0.0-SNAPSHOT
package=com.aem.ecm
appId=ecm
appTitle=ECM
aemVersion=cloud
sdkVersion=2026.9.28187.20260911T134704Z-260800
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=general
singleCountry=y
includeDispatcherConfig=y
includeCif=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
